//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Fpga(

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
// instancia

Circuito_topo u1(.D(SW[0]), .N1(SW[3]), .N2(SW[2]), .N3(SW[1]), .s0(HEX0[0]), .s1(HEX0[1]), .s2(HEX0[2]), .s3(HEX0[3]), .s4(HEX0[4]), .s5(HEX0[5]), .s6(HEX0[6]));

//=======================================================
//  Structural coding
//=======================================================



endmodule